name: Run PowerShell script
on: push
jobs:
  run-script:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run PowerShell script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        $csv = Import-Csv -Delimiter ';' -Path .\feed.csv

        $yesterday8AM = (Get-Date).AddDays(-1).Date.AddHours(8)
        $today8AM = (Get-Date).Date.AddHours(8)

        $linkProperty = @{
            Name = "Link"
            Expression = {"`<a href=$($_.Link) target=_blank`>Link to post`</a`>"}
        }

        foreach ($item in $csv) {
            $articles = .\Get-RSS.ps1 -Url $item.url
            $html += "<h1>$($item.Name)</h1>"
            $html += $articles | 
            Where-Object {$_.date -ge $yesterday8AM -and $_.date -lt $today8AM} | 
            Select-Object Date,Title,$linkProperty | 
            ConvertTo-Html -Head ''
            $html = $html -replace '&lt;', '<' -replace '&gt;', '>'
        }
        $repo = "bastien-w/Get-RSS"
        $token = "${{ env.ACCESS_TOKEN }}"
        $headers = @{
            Authorization = "token $token"
        }
        $IssueTitle = get-date -Format "dd/MM/yyyy - HH:mm:ss"
        $body = @{
            title = $IssueTitle
            body = $html
        } | ConvertTo-Json
        Invoke-RestMethod -Method Post -Headers $headers -Body $body -ContentType "application/json" -Uri "https://api.github.com/repos/$repo/issues"