name: Run PowerShell script
on:
  schedule:
    - cron: '0 6 * * 2-6'  
  workflow_dispatch:
jobs:
  run-script:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Run PowerShell script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        $csv = Import-Csv -Delimiter ';' -Path .\feed.csv
        $Repo = "bastien-w/Get-RSS"
        $Token = "${{ env.ACCESS_TOKEN }}"
        $IssueTitle = get-date -Format "dd/MM/yyyy - HH:mm:ss"
        $yesterday8AM = (Get-Date).AddDays(-1).Date.AddHours(8)
        $today8AM = (Get-Date).Date.AddHours(8)

        $linkProperty = @{
            Name = "Link"
            Expression = {"`<a href=$($_.Link) target=_blank`>$($_.Title)`</a`>"}
        }

        foreach ($item in $csv) {
            $articles = .\Get-RSS.ps1 -Url $item.url
            $html += "<h1>$($item.Name)</h1>"
            $html += $articles | 
            Where-Object {$_.date -ge $yesterday8AM -and $_.date -lt $today8AM} | 
            Select-Object Date,$linkProperty | 
            ConvertTo-Html -Head ''
            $html = $html -replace '&lt;', '<' -replace '&gt;', '>'
        }

      .\New-GHIssue.ps1 -Repository $Repo -Token $Token -Title $IssueTitle -Content $html