name: Run PowerShell script
on: push
jobs:
  run-script:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run PowerShell script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        .\main.ps1
        $repo = "bastien-w/Get-RSS"
        $token = "${{ env.ACCESS_TOKEN }}"
        $headers = @{
            Authorization = "token $token"
        }
        $IssueTitle = get-date
        $body = @{
            title = $IssueTitle
            body = $htmlTable
        } | ConvertTo-Json
        Invoke-RestMethod -Method Post -Headers $headers -Body $body -ContentType "application/json" -Uri "https://api.github.com/repos/$repo/issues"